# Codespell configuration is within pyproject.toml
---
name: Codespell

on:
  push:
    branches: [main]
    paths-ignore:
      - 'resources/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'resources/**'

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Annotate locations with typos
        uses: codespell-project/codespell-problem-matcher@v1
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
